"""
Pyrl Core Module
Core components of the Pyrl language interpreter.
Based on Lark parser with integrated lexer.
"""

# Main VM (from vm package)
from .vm import (
    PyrlVM,
    run,
    run_file,
    create_vm,
    PyrlFunction,
    PyrlClass,
    PyrlInstance,
    PyrlMethod,
    Environment,
    PyrlRuntimeError,
    ReturnValue,
    BreakException,
    ContinueException,
    BUILTINS,
    CONSTANTS,
    HTTP_BUILTINS,
    DB_BUILTINS,
    CRYPTO_BUILTINS,
)

# Lark parser (primary parser)
from .lark_parser import (
    PyrlLarkParser,
    parse_lark,
    parse_file_lark,
    print_ast,
    GRAMMAR,
    # AST nodes from Lark parser
    Program,
    ScalarVar,
    ArrayVar,
    HashVar,
    FuncVar,
    IdentRef,
    NumberLiteral,
    StringLiteral,
    BooleanLiteral,
    NoneLiteral,
    ArrayLiteral,
    HashLiteral,
    RegexLiteral,
    BinaryOp,
    UnaryOp,
    Assignment,
    HashAccess,
    ArrayAccess,
    FunctionCall,
    FunctionDef,
    IfStatement,
    ForLoop,
    WhileLoop,
    ReturnStatement,
    PrintStatement,
    AssertStatement,
    TestBlock,
    VueComponent,
    # OOP and Anonymous Functions
    Block,
    AnonymousFuncDef,
    ClassDef,
    MethodDef,
    PropertyDef,
    MethodCall,
)

# Exceptions
from .exceptions import (
    PyrlError,
    ParseError,
    RuntimeError,
    VariableError,
    FunctionError,
    TypeError_,
    IndexError_,
    KeyError_,
    ImportError_,
    ReturnException,
    BreakException,
    ContinueException,
)


__all__ = [
    # VM
    'PyrlVM',
    'run',
    'run_file',
    'create_vm',
    'PyrlFunction',
    'PyrlClass',
    'PyrlInstance',
    'PyrlMethod',
    'Environment',
    'PyrlRuntimeError',
    'ReturnValue',
    'BreakException',
    'ContinueException',

    # Parser (Lark-based)
    'PyrlLarkParser',
    'parse_lark',
    'parse_file_lark',
    'print_ast',
    'GRAMMAR',

    # AST Nodes (Lark-based)
    'Program',
    'ScalarVar',
    'ArrayVar',
    'HashVar',
    'FuncVar',
    'IdentRef',
    'NumberLiteral',
    'StringLiteral',
    'BooleanLiteral',
    'NoneLiteral',
    'ArrayLiteral',
    'HashLiteral',
    'RegexLiteral',
    'BinaryOp',
    'UnaryOp',
    'Assignment',
    'HashAccess',
    'ArrayAccess',
    'FunctionCall',
    'FunctionDef',
    'IfStatement',
    'ForLoop',
    'WhileLoop',
    'ReturnStatement',
    'PrintStatement',
    'AssertStatement',
    'TestBlock',
    'VueComponent',
    'Block',
    'AnonymousFuncDef',
    'ClassDef',
    'MethodDef',
    'PropertyDef',
    'MethodCall',

    # Exceptions
    'PyrlError',
    'ParseError',
    'RuntimeError',
    'VariableError',
    'FunctionError',
    'TypeError_',
    'IndexError_',
    'KeyError_',
    'ImportError_',
    'ReturnException',

    # Builtins
    'BUILTINS',
    'CONSTANTS',
    'HTTP_BUILTINS',
    'DB_BUILTINS',
    'CRYPTO_BUILTINS',
]
